apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: "managed-premium"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  storageClassName: "managed-premium"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: monitoring
spec:
  secretName: tls-secret
  dnsNames:
    - dev-monitoring.datacomcpnz.com
  acme:
    config:
      - http01:
          ingressClass: public-nginx-ingress
        domains:
          - dev-monitoring.datacomcpnz.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
